#+INCLUDE: ../publishing/jekyll_base.org
#+MACRO: layout post
#+MACRO: title Implications of a Petroleum-less Military
#+MACRO: date 2010-10-25
#+MACRO: tags military energy
#+INCLUDE: ../publishing/jekyll_yaml.org

* What are the implications of The American Military Infrastructure going green?

A new [[http://www.cnas.org/files/documents/publications/CNAS_Working_Paper_EnergyMap_InitialFindings_Burke_Dec2008_1.pdf][“Center for a New American Security” study]] aimed at exploring a post-petroleum military makes some great points as to the why, and the how, but only hints at some of the broader repercussions.

#+BEGIN_QUOTE
 “A successful transition away from petroleum will produce financial, operational and strategic gains. Reducing dependence on petroleum will help ensure the long-term ability of the military to carry out its assigned missions --- and help ensure the security of the nation...Finally, moving beyond petroleum will allow DOD to lead in the development of innovative technologies that can benefit the nation more broadly, while signaling to the world that the United States has as innovative and adaptable force.”
#+END_QUOTE

With petroleum comprising 77% of the DOD's energy use ,and the DOD comprising aprox. 80% of the federal governments energy use, the DOD's plan to replace petroleum energy use in the military over the next 40 years is going to create a long term market for alternative energy suppliers and researchers. But, how will this open field be distributed among the current system of wealth? Can we take control, through innovation, to pull power away from the companies that have monopolies on energy and distribute it to the people?
